object Versions {
  lazy val scalaVersion = "2.13.5"
  lazy val slickVersion = "3.3.3"
  lazy val playVersion = "5.1.0"
  lazy val playCirceVersion = "2812.0"
  lazy val playJdbcVersion = "2.8.8"
  lazy val playGuiceVersion = "2.8.8"
  lazy val playSlickVersion = "5.0.0"
  lazy val playSlickEvolutionsVersion = "5.0.0"
  lazy val postgresqlJdbcVersion = "42.2.20"
  lazy val h2JdbcVersion = "1.4.199"
  lazy val catsEffectVersion = "3.1.0"
  lazy val catsEffectTestingVersion = "1.1.0"
  lazy val circeCoreVersion = "0.12.2"
  lazy val circeGenericVersion = "0.12.2"
  lazy val circeGenericExtrasVersion = "0.12.2"
  lazy val circeParserVersion = "0.12.2"
  lazy val scalaTestVersion = "3.2.7"
}
