version: "3.7"
services:
    placeholder:
        image: busybox
        networks:
        - database
        - broker
networks:
    database:
        name: frisbee_database
        driver: bridge
    broker:
        name: frisbee_broker
        driver: bridge