version: "3.7"
services:
    database:
        image: postgres:13.2-alpine
        command: postgres -c 'max_connections=500'
        restart: always
        ports:
        - 127.0.0.1:5432:5432
        volumes:
        - ./data:/var/lib/postgresql/data
        deploy:
            resources:
                limits:
                    cpus: "0.2"
                    memory: 256M
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: dip
