[package]
name = "agent"
version = "0.1.0"
authors = ["Krisjanis Veinbahs <krisjanis.veinbahs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
tokio = { version = "1.12.0", features = ["full"] }
tokio-tungstenite = "0.15.0"
env_logger = "0.9.0"
url = "2.0.0"
clap = "3.0.0-beta.4"
